#!/usr/bin/env bash
set -eufo pipefail

echo "Publishing as $(npm whoami)."

if ! npm outdated --long; then
  read -rp "Continue? [y/N] " choice
  if [[ "${choice-n}" != 'y' ]]; then
    echo 'Package distribution aborted.'
    exit 2
  fi
fi

source 'node_modules/sanctuary-scripts/functions'

pkg="$(get repo-name)"
files="$(get source-files)"

sed --in-place "s/$pkg@0.0.0/$pkg@$VERSION/" "$files"
sed --in-place "s/$pkg@$PREVIOUS_VERSION/$pkg@$VERSION/" "$files"

git add -- "$files"

npm run build

sanctuary-prepublish "$@"
